#pragma once

const char DASHBOARD_HTML[] PROGMEM = R"HTML(
<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Soil Monitor</title><style>
:root{--bg:#07110d;--panel:#102019;--panel2:#152a21;--text:#eefaf2;--muted:#91ae9c;--green:#48dc83;--yellow:#ffd166;--red:#ff6b6b;--cyan:#5ee7e7}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#183729 0,var(--bg) 44%);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;min-height:100vh}.wrap{width:min(1100px,calc(100% - 28px));margin:auto;padding:28px 0 48px}header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:22px}h1{font-size:clamp(25px,5vw,42px);margin:0;letter-spacing:-.04em}.sub{color:var(--muted);font-size:13px;margin-top:4px}.badge{padding:8px 13px;border-radius:999px;background:#25352d;color:var(--muted);font-weight:800;font-size:12px;letter-spacing:.07em}.badge.live{background:#123d25;color:var(--green)}.badge.off{background:#431d20;color:var(--red)}.panel{background:linear-gradient(145deg,rgba(23,48,37,.96),rgba(12,27,20,.98));border:1px solid #284638;border-radius:22px;box-shadow:0 20px 70px #0007}.hero{display:grid;grid-template-columns:1fr 1.15fr;gap:22px;padding:26px;margin-bottom:18px}.moist-label,.eyebrow{color:var(--muted);font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.moist{font-size:clamp(70px,13vw,128px);font-weight:900;letter-spacing:-.08em;line-height:.95;margin:11px 0 14px}.condition{font-size:18px;font-weight:800}.bar{height:13px;background:#08130e;border-radius:20px;overflow:hidden;margin-top:18px}.bar>i{display:block;width:0;height:100%;border-radius:20px;background:var(--green);transition:.6s}.analysis{display:flex;flex-direction:column;justify-content:center;background:#0b1913;border:1px solid #233e31;border-radius:17px;padding:22px}.analysis h2{font-size:23px;margin:7px 0 9px}.analysis p{color:#b8d1c1;line-height:1.55;margin:0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.card{padding:18px;min-height:118px}.value{font-weight:850;font-size:27px;margin-top:12px;letter-spacing:-.03em}.detail{color:var(--muted);font-size:12px;margin-top:5px}.chart{padding:22px;margin-bottom:18px}.chart-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:12px}.chart h2{margin:5px 0 0;font-size:20px}.legend{color:var(--muted);font-size:12px}canvas{display:block;width:100%;height:260px;background:#091611;border-radius:13px}.foot{display:flex;justify-content:space-between;gap:12px;color:var(--muted);font-size:12px;padding:0 4px}.foot a{color:var(--cyan)}@media(max-width:760px){.hero{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:420px){.grid{grid-template-columns:1fr}.hero{padding:18px}.wrap{width:min(100% - 18px,1100px)}}
</style></head><body><div class="wrap">
<header><div><h1>Soil Monitor</h1><div class="sub">Long-range ESP-NOW garden telemetry</div></div><div id="status" class="badge">CONNECTING</div></header>
<section class="panel hero"><div><div class="moist-label">Current moisture</div><div id="moist" class="moist">--%</div><div id="condition" class="condition">Waiting for sensor</div><div class="bar"><i id="moistBar"></i></div></div><div class="analysis"><div class="eyebrow">Plant insight</div><h2 id="analysisTitle">Collecting data</h2><p id="analysisText">The dashboard will generate an interpretation as soon as the first sensor packet arrives.</p></div></section>
<section class="grid">
 <div class="panel card"><div class="eyebrow">1-hour average</div><div id="avg" class="value">--%</div><div id="range" class="detail">Range --</div></div>
 <div class="panel card"><div class="eyebrow">Trend</div><div id="trend" class="value">--</div><div id="delta" class="detail">Change --</div></div>
 <div class="panel card"><div class="eyebrow">Wireless strength</div><div id="signal" class="value">--%</div><div id="rssi" class="detail">RSSI -- dBm</div></div>
 <div class="panel card"><div class="eyebrow">Packet reliability</div><div id="reliability" class="value">--%</div><div id="packets" class="detail">0 packets</div></div>
 <div class="panel card"><div class="eyebrow">Sensor output</div><div id="voltage" class="value">-- V</div><div id="raw" class="detail">Raw ADC --</div></div>
 <div class="panel card"><div class="eyebrow">Last reading</div><div id="age" class="value">--</div><div id="sequence" class="detail">Sequence --</div></div>
 <div class="panel card"><div class="eyebrow">Sample history</div><div id="samples" class="value">0</div><div class="detail">5-minute samples</div></div>
 <div class="panel card"><div class="eyebrow">Gateway</div><div id="gateway" class="value">Online</div><div id="ip" class="detail">Loading address</div></div>
</section>
<section class="panel chart"><div class="chart-head"><div><div class="eyebrow">Moisture history</div><h2>Last 60 minutes</h2></div><div class="legend">0% dry · 100% wet</div></div><canvas id="plot"></canvas></section>
<div class="foot"><span>Refreshes every 2 seconds · <b>soil-monitor.local</b></span><span>Hold BOOT during reset to change Wi-Fi</span></div>
</div><script>
const $=id=>document.getElementById(id);let historyData=[];
function colorFor(v){return v<25?'var(--red)':v<45?'var(--yellow)':'var(--green)'}
function insight(v,trend){if(v<25)return['Water recommended','The soil is dry. Water the plant and confirm that the reading begins to rise.'];if(v<45)return['Moisture is getting low',trend==='Falling'?'The soil is drying. Plan to water soon if the downward trend continues.':'The soil is slightly dry but currently usable. Watch the trend.'];if(v<80)return['Moisture is in the healthy range','No watering is indicated from the current reading. Continue monitoring the one-hour trend.'];return['Soil is very wet','Pause watering and verify drainage. Persistently high moisture may stress roots.']}
async function live(){try{const d=await fetch('/api/data',{cache:'no-store'}).then(r=>r.json());$('status').textContent=d.linked?'LIVE':'OFFLINE';$('status').className='badge '+(d.linked?'live':'off');$('moist').textContent=d.valid?d.moisture+'%':'--%';$('condition').textContent=d.valid?d.condition:'Check sensor wiring';$('moist').style.color=d.valid?colorFor(d.moisture):'var(--red)';$('moistBar').style.width=(d.valid?d.moisture:0)+'%';$('moistBar').style.background=colorFor(d.moisture);$('avg').textContent=d.samples?d.average.toFixed(1)+'%':'--%';$('range').textContent=d.samples?'Range '+d.minimum+'–'+d.maximum+'%':'Range --';$('trend').textContent=d.trend;$('delta').textContent=(d.delta>=0?'+':'')+d.delta.toFixed(1)+' points';$('signal').textContent=d.signal+'%';$('rssi').textContent='RSSI '+d.rssi+' dBm';$('reliability').textContent=d.reliability.toFixed(1)+'%';$('packets').textContent=d.received+' received · '+d.missed+' missed';$('voltage').textContent=(d.millivolts/1000).toFixed(2)+' V';$('raw').textContent='Raw ADC '+d.raw;$('age').textContent=d.age_ms<1500?'Now':Math.round(d.age_ms/1000)+'s ago';$('sequence').textContent='Sequence '+d.sequence;$('samples').textContent=d.samples;$('ip').textContent=d.ip;const i=insight(d.moisture,d.trend);$('analysisTitle').textContent=i[0];$('analysisText').textContent=i[1]}catch(e){$('status').textContent='GATEWAY ERROR';$('status').className='badge off'}}
async function history(){try{historyData=await fetch('/api/history',{cache:'no-store'}).then(r=>r.json());draw()}catch(e){}}
function draw(){const c=$('plot'),r=c.getBoundingClientRect(),q=devicePixelRatio||1;c.width=r.width*q;c.height=r.height*q;const x=c.getContext('2d');x.scale(q,q);const w=r.width,h=r.height,p=38;x.clearRect(0,0,w,h);x.strokeStyle='#294438';x.fillStyle='#729080';x.font='11px system-ui';x.lineWidth=1;[0,25,50,75,100].forEach(v=>{const y=h-p-(v/100)*(h-p*1.45);x.beginPath();x.moveTo(p,y);x.lineTo(w-12,y);x.stroke();x.fillText(v+'%',4,y+4)});const a=historyData.moisture||[];if(a.length<2)return;x.strokeStyle='#48dc83';x.lineWidth=3;x.lineJoin='round';x.beginPath();a.forEach((v,i)=>{const xx=p+i*(w-p-14)/(a.length-1),yy=h-p-(v/100)*(h-p*1.45);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke();x.fillStyle='#729080';x.fillText('60m ago',p,h-10);x.fillText('now',w-34,h-10)}
addEventListener('resize',draw);live();history();setInterval(live,2000);setInterval(history,10000);
</script></body></html>
)HTML";

const char WIFI_SETUP_HTML[] PROGMEM = R"HTML(
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Soil Monitor Wi-Fi Setup</title><style>
body{margin:0;background:#07110d;color:#eefaf2;font-family:system-ui;display:grid;place-items:center;min-height:100vh}.box{width:min(430px,calc(100% - 32px));background:#13271e;border:1px solid #315441;border-radius:22px;padding:28px;box-sizing:border-box}h1{margin:0 0 8px}p{color:#a9c3b3;line-height:1.45}label{display:block;margin:18px 0 6px;font-weight:700}input{width:100%;box-sizing:border-box;padding:13px;border-radius:10px;border:1px solid #42644f;background:#09150f;color:white;font-size:16px}button{width:100%;margin-top:22px;border:0;border-radius:11px;padding:14px;background:#48dc83;color:#06200f;font-weight:900;font-size:16px}.note{font-size:12px;color:#8cab98;margin-top:16px}a{color:#5ee7e7}
</style></head><body><form class="box" method="post" action="/save-wifi"><h1>Soil Monitor</h1><p>Connect the display gateway to your home Wi-Fi. It will restart and become available at <b>http://soil-monitor.local</b>.</p><label>Home Wi-Fi name (SSID)</label><input name="ssid" maxlength="32" required autocomplete="off"><label>Wi-Fi password</label><input name="password" type="password" maxlength="63" autocomplete="new-password"><h2>Secure cloud upload</h2><p>Leave these three fields empty until the cloud API is deployed. Existing cloud settings are preserved when they are blank.</p><label>Cloud ingest URL</label><input name="cloud_api_url" type="url" maxlength="220" placeholder="https://…/soil-api/v1/ingest" autocomplete="off"><label>Cloud device ID</label><input name="cloud_device_id" maxlength="64" placeholder="garden-sensor-1" autocomplete="off"><label>Cloud ingest secret</label><input name="cloud_ingest_secret" type="password" minlength="32" maxlength="256" autocomplete="new-password"><button type="submit">Save and connect</button><div class="note">Credentials stay in the gateway's local flash and are never sent to GitHub Pages. Use a 2.4 GHz network; ESP32-S3 does not connect to 5 GHz-only Wi-Fi.</div></form></body></html>
)HTML";
